"""
Auto-generated abstract methods based on JSON-RPC OpenAPI specification.
"""

from abc import ABC, abstractmethod


class BlockchainAdapter(ABC):
    @abstractmethod
    async def eth_getbalance(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_getcode(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_getproof(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_getstorageat(self, param1: str, param2: str, param3: str) -> str: ...
    @abstractmethod
    async def eth_gettransactioncount(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_blocknumber(self) -> str: ...
    @abstractmethod
    async def eth_getblockbynumber(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_getblocktransactioncountbyhash(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_getblocktransactioncountbynumber(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_newblockfilter(self) -> str: ...
    @abstractmethod
    async def eth_chainid(self) -> str: ...
    @abstractmethod
    async def eth_syncing(self) -> str: ...
    @abstractmethod
    async def net_listening(self) -> str: ...
    @abstractmethod
    async def net_peercount(self) -> str: ...
    @abstractmethod
    async def web3_clientversion(self) -> str: ...
    @abstractmethod
    async def debug_tracetransaction(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def debug_traceblockbyhash(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def debug_traceblockbynumber(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def debug_tracecall(self, param1: str, param2: str, param3: str) -> str: ...
    @abstractmethod
    async def debug_tracetransaction(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def trace_block(self, param1: str) -> str: ...
    @abstractmethod
    async def trace_transaction(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_call(self, to_: str, data: str) -> str: ...
    @abstractmethod
    async def eth_sendrawtransaction(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_simulatev1(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_getfilterchanges(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_uninstallfilter(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_estimategas(self, from_: str, to_: str) -> str: ...
    @abstractmethod
    async def eth_gasprice(self) -> str: ...
    @abstractmethod
    async def eth_maxpriorityfeepergas(self) -> str: ...
    @abstractmethod
    async def eth_getlogs(self, fromBlock: str, address: str, topics: str) -> str: ...
    @abstractmethod
    async def eth_newfilter(self, fromBlock: str, address: str, topics: str) -> str: ...
    @abstractmethod
    async def eth_getblockreceipts(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_gettransactionbyblockhashandindex(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_gettransactionbyblocknumberandindex(self, param1: str, param2: str) -> str: ...
    @abstractmethod
    async def eth_gettransactionbyhash(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_gettransactionreceipt(self, param1: str) -> str: ...
    @abstractmethod
    async def eth_newpendingtransactionfilter(self) -> str: ...
